workflows:
  build-android-ios:
    name: Inseek Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ios --release
 
